### ISSUE TITLE
Hardcoded 'http://' protocol in ioquake3.js; "mixed content" error in browser

### ISSUE THREAD

**Issue by djpbessems** [criticalstack/quake-kube#17]
There are three occurences where the URI protocol is hardcoded as `http://` in ioquake3.js; this prevents running this behind a reverse proxy with TLS due to the browser blocking mixed content.

**Comment by ChrisRx** [comment]
I think it could probably be modified to replace those instances of hardcoded scheme with `document.location.protocol + '//example.com'` or something like that, interested in giving it a shot?

**Comment by djpbessems** [comment]
Sure, just let me know how :)

**Comment by campbel** [comment]
The suggested fix wasn't quite enough. There is also the issue of the port being selected (comes from host in index.html) and also the websocket protocol. I fixed both of these in my PR and have it running on my kubernetes environment with https.

**Comment by alexellis** [comment]
I'm getting exactly the same issue when running this over an [inlets tunnel](https://docs.inlets.dev) - the idea was to invite friends to play a "WAN party"

**Comment by ChrisRx** [comment]
Ok I think this should be fixed by #20, if it isn't we can reopen.
