### ISSUE TITLE
tls through reverse proxy support ?

### ISSUE THREAD

**Issue by sokoow** [criticalstack/quake-kube#22]
Hi All,

Nice work, well done! I got a question on running this through a tls reverse proxy.

So, when I run it through tls, I get this:

Form submission canceled because the form is not connected (index)
ioquake3.js:116 initial sync completed in 0.01 seconds
ioquake3.js:15511 Mixed Content: The page at 'https://quake.domain.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://quake.domain.com/info'. This request has been blocked; the content must be served over HTTPS.

did you think about any way of addressing this ? Or maybe there's a flag somewhere... ? :)

**Comment by ChrisRx** [comment]
This sounds potentially like #17, I think at nearly the same time you opened this issue, a fix for it was being merged in #20.  Have you had a chance to try it with the newer image version v1.0.6?

**Comment by sokoow** [comment]
ah true, closin
